# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 00322c0c7a81ab3671ef9c3494559e88db5603edad37b73c0a324ac973ce309ed82b20812dd606991be1caca6769d70096ec3008f7d054f0cac8fdaaedf9cceb

test:
  secret_key_base: 95eec10b308bce7a19e73df7196f2f0bab45fd5ccb660da3415f88e583db4413a4c3254fd98628f45b18d3bd7112e37d3e6c2574c16b4d2d3b3e80609fb780d9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
